#!/usr/bin/env python
#
# Mimon - lightweight load monitor
# Copyright (C) 2009  Daniel Milde <info@milde.cz>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/gpl-3.0.html>.

config_file = '/etc/mimon.conf'
target_dir  = './'

import sys
import os
import time
import signal
import mimon.config

try:
	import rrdtool
except Exception, e:
	print "Package python-rrdtool not installed"
	sys.exit(1)

config = mimon.config.read(config_file)

def usage():
	print 'Usage: ' + sys.argv[0] + ' target_directory | --help'
	sys.exit(0)

if len(sys.argv) > 1:
	if sys.argv[1] == '--help' or sys.argv[1][0] == '-':
		usage()
	else:
		target_dir = sys.argv[1]

mods = []
for m in config['modules']:
	__import__("mimon."+m)
	mods.append(sys.modules["mimon."+m])

for m in mods: m.graph(config['data_dir'], target_dir)
